services:
  db:
    container_name: db
    image: mariadb:${MARIADB_VERSION:-latest}  # https://hub.docker.com/_/mariadb
    volumes:
      # NOTE Without persistent storage, rebuilding dev container will be drop any changes on non host mounted directory.
      - "../mariadb:/var/lib/mysql"
    configs:
      - source: mariadb-conf
        target: /etc/mysql/mariadb.conf.d/99-my.cnf
    environment:
      # MariaDB Server Docker Official Image supports `MYSQL_*` variants.
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME:-wordpress}
      MYSQL_USER: ${WORDPRESS_DB_USER:-wordpress}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD:-wordpress}
      # https://mariadb.com/kb/en/mariadb-server-docker-official-image-environment-variables/
      MARIADB_AUTO_UPGRADE: "yes"
    healthcheck:
      # https://mariadb.com/kb/en/using-healthcheck-sh/#comment_6578
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      start_period: 5s
      interval: 30s
      timeout: 5s
      retries: 100


# You can override config in docker-compose.yml file that includes this service.
configs:
  mariadb-conf:
    content: |+
      # Custom MariaDB configuration goes here.
