services:
  db:
    image: mariadb:${MARIADB_VERSION:-latest}  # https://hub.docker.com/_/mariadb
    volumes:
      - "../mariadb:/var/lib/mysql"
      # For non environment variables configuration, use a custom configuration file.
      # - "../mariadb.cnf:/etc/mysql/mariadb.conf.d/99-my.cnf"
    environment:
      # MariaDB Server Docker Official Image supports `MYSQL_*` variants.
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME:-wordpress}
      MYSQL_USER: ${WORDPRESS_DB_USER:-wordpress}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD:-wordpress}
      # https://mariadb.com/kb/en/mariadb-server-docker-official-image-environment-variables/
      MARIADB_AUTO_UPGRADE: "yes"
    healthcheck:
      # https://mariadb.com/kb/en/using-healthcheck-sh/#comment_6578
      interval: 30s
      timeout: 30s
      retries: 3
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
