services:
  # NOTE "." means ".devcontainer", NOT this file's parent directory.
  # NOTE Without persistent storage, rebuilding dev container will be drop any changes on non host mounted directory.

  # devcontainer:
  #   environment:
  #     WORDPRESS_SETUP_SCRIPT: "/var/www/html/.workspace/PATH/TO/SETUP_SCRIPT.sh"
  #   volumes:
  #     # your plugin
  #     - "../src:/var/www/html/wp-content/plugins/YOUR_PLUGIN_SLUG"
  #     # persistent storage
  #     - "../wp-content:/var/www/html/wp-content"
  #     # SSL certificate
  #     - "your-ssl.key:/var/www/ssl-cert-snakeoil.key:ro"
  #     - "your-ssl.pem:/var/www/ssl-cert-snakeoil.pem:ro"

  # mysql:
  #   volumes:
  #     # persistent storage
  #     - "../mysql:/var/lib/mysql"

  # Example for using `mariadb` instead of `mysql`.
  # mysql:
  #   image: mariadb:10.6  # https://hub.docker.com/_/mariadb
  #   volumes:
  #     - "../mariadb:/var/lib/mysql"
  #     # For non environment variables configuration, use a custom configuration file.
  #     - "../mariadb.cnf:/etc/mysql/mariadb.conf.d/99-my.cnf"
  #   environment:
  #     # MariaDB Server Docker Official Image supports `MYSQL_*` variants.
  #     # https://mariadb.com/kb/en/mariadb-server-docker-official-image-environment-variables/
  #     MARIADB_AUTO_UPGRADE: "yes"
  #   healthcheck:
  #     # https://mariadb.com/kb/en/using-healthcheck-sh/#comment_6578
  #     interval: 30s
  #     timeout: 30s
  #     retries: 3
  #     test:
  #       [
  #         "CMD",
  #         "healthcheck.sh",
  #         "--su-mysql",
  #         "--connect",
  #         "--innodb_initialized"
  #       ]

  # NOTE Be aware of increased resource consumption.
  # selenium:
  #   extends:
  #     file: common.yml
  #     service: selenium
  #   # Example for port forwarding (selenium:80 <-- devcontainer:80)
  #   build:
  #     dockerfile_inline: |+
  #       FROM selenium/standalone-chrome
  #       RUN sudo apt-get update; sudo apt-get install -yq socat; \
  #         { \
  #           echo [program:portforward]; \
  #           echo priority=20; \
  #           echo command=/usr/bin/socat TCP-LISTEN:80,reuseaddr,fork TCP:devcontainer:80; \
  #           echo autostart=true; \
  #           echo autorestart=false; \
  #           echo startsecs=0; \
  #           echo startretries=0; \
  #           echo ";Logs"; \
  #           echo redirect_stderr=false; \
  #           echo stdout_logfile=/var/log/supervisor/socat-stdout.log; \
  #           echo stderr_logfile=/var/log/supervisor/socat-stderr.log; \
  #           echo stdout_logfile_maxbytes=50MB; \
  #           echo stderr_logfile_maxbytes=50MB; \
  #           echo stdout_logfile_backups=5; \
  #           echo stderr_logfile_backups=5; \
  #           echo stdout_capture_maxbytes=50MB; \
  #           echo stderr_capture_maxbytes=50MB; \
  #         } | sudo tee /etc/supervisor/conf.d/port-forward.conf
  #   environment:
  #     LANGUAGE: ja_JP.UTF-8
  #     SE_VNC_NO_PASSWORD: "1"  # Set SE_VNC_NO_PASSWORD to "1" to disable VNC password.
  #     # See https://github.com/SeleniumHQ/docker-selenium/ for more SE_* options.
  #   networks:
  #     - wordpress
  #   # https://github.com/SeleniumHQ/docker-selenium/issues/2045
  #   ulimits:
  #     nofile:
  #       soft: 65536
  #       hard: 65536
