services:
  # NOTE "." means ".devcontainer", NOT this file's parent directory.
  # NOTE Without persistent storage, rebuilding dev container will be drop any changes on non host mounted directory.

  # devcontainer:
  #   environment:
  #     WORDPRESS_SETUP_SCRIPT: "/var/www/html/.workspace/PATH/TO/SETUP_SCRIPT.sh"
  #   volumes:
  #     # your plugin
  #     - "../src:/var/www/html/wp-content/plugins/YOUR_PLUGIN_SLUG"
  #     # persistent storage
  #     - "../wp-content:/var/www/html/wp-content"
  #     # SSL certificate
  #     - "your-ssl.key:/var/www/ssl-cert-snakeoil.key:ro"
  #     - "your-ssl.pem:/var/www/ssl-cert-snakeoil.pem:ro"

  # mysql:
  #   volumes:
  #     # persistent storage
  #     - "../mysql:/var/lib/mysql"

  # Example for using `mariadb` instead of `mysql`.
  # mysql:
  #   image: mariadb:10.6  # https://hub.docker.com/_/mariadb
  #   volumes:
  #     - "../mariadb:/var/lib/mysql"
  #     # For non environment variables configuration, use a custom configuration file.
  #     - "../mariadb.cnf:/etc/mysql/mariadb.conf.d/99-my.cnf"
  #   environment:
  #     # MariaDB Server Docker Official Image supports `MYSQL_*` variants.
  #     # https://mariadb.com/kb/en/mariadb-server-docker-official-image-environment-variables/
  #     MARIADB_AUTO_UPGRADE: "yes"
  #   healthcheck:
  #     # https://mariadb.com/kb/en/using-healthcheck-sh/#comment_6578
  #     interval: 30s
  #     timeout: 30s
  #     retries: 3
  #     test:
  #       [
  #         "CMD",
  #         "healthcheck.sh",
  #         "--su-mysql",
  #         "--connect",
  #         "--innodb_initialized"
  #       ]

  # NOTE Be aware of increased resource consumption.
  # selenium:
  #   environment:
  #     LANGUAGE: ja_JP.UTF-8
  #   ports:
  #     - "4444:4444"
