include:
  - db-mysql.docker-compose.yml
  - smtp-mailpit.docker-compose.yml
  - wp-cron.docker-compose.yml


services:

  devcontainer:
    extends:
      file: devcontainer-base.docker-compose.yml
      service: devcontainer-base

    configs:
      - source: wpcli-yml
        target: /var/www/html/wp-cli.yml

    volumes:
      - "..:/var/www/html/.workspace"

      # persistent storage
      - "../.vscode:/var/www/html/.vscode"
      - "../wp-content:/var/www/html/wp-content"

      # your plugin
      # - "../src:/var/www/html/wp-content/plugins/YOUR_PLUGIN_SLUG"

      # SSL certificate
      # - "your-ssl.key:/var/www/ssl-cert-snakeoil.key:ro"
      # - "your-ssl.pem:/var/www/ssl-cert-snakeoil.pem:ro"

    # NOTE: `extends` will remove referenced `depends_on` entries from the base service. You need to redefine them here if necessary.
    depends_on:
      db:
        condition: service_healthy
      smtp:
        condition: service_healthy


configs:
  wpcli-yml:
    content: |+
      apache_modules:
        - mod_rewrite
  mysql-conf:
    content: |+
      # [mysqld]
      # You can override MySQL configuration here.
