services:

  # https://hub.docker.com/_/mysql
  mysql:
    image: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME:-wordpress}
      MYSQL_USER: ${WORDPRESS_DB_USER:-wordpress}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD:-wordpress}
    # https://stackoverflow.com/a/54854239/3622941
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 300s
      interval: 5s
      timeout: 5s
      retries: 55
    networks:
      - wordpress


  # https://hub.docker.com/r/selenium/standalone-chrome
  # https://github.com/SeleniumHQ/docker-selenium
  # http://localhost:4444 --> Sessions --> Recording icon like 📹--> LiveView with password "secret"
  selenium:
    image: selenium/standalone-chrome
    healthcheck:
      test: /opt/bin/check-grid.sh --host 0.0.0.0 --port 4444
      interval: 15s
      timeout: 300s
      retries: 5
    shm_size: 2g
    networks:
      - wordpress


  # https://github.com/mailhog/MailHog
  mailhog:
    image: mailhog/mailhog
    networks:
      - wordpress


  # https://hub.docker.com/_/wordpress
  wordpress:
    build:
      context: .
      dockerfile: wordpress-base.Dockerfile
      target: wordpress-base
      # args:
      #   TAG: php8.1
    environment: &wordpress_environment
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME:-wordpress}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER:-wordpress}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD:-wordpress}
      # WORDPRESS_SETUP_SCRIPT: "/var/www/html/.workspace/PATH/TO/SETUP_SCRIPT.sh"
      WORDPRESS_CONST_AUTOMATIC_UPDATER_DISABLED: 1
      WORDPRESS_CONFIG_EXTRA: |+
        require_once '/var/www/html/.workspace/.devcontainer/wp-config-injection.php';
      # WORDPRESS_DEBUG: "yes"  # optional, default: no
      # WORDPRESS_INSTALL_TITLE: "WordPress in devcontainer"  # optional, default: WordPress in docker
      # WORDPRESS_INSTALL_ADMIN_USER: "admin"  # optional, default: admin
      # WORDPRESS_INSTALL_ADMIN_PASSWORD: "password"  # optional, default: password
      # WORDPRESS_INSTALL_ADMIN_EMAIL: "admin@wordpress.local"  # optional, default: admin@wordpress.local
      # WORDPRESS_LOCALE: "en_US"  # optional, default: en_US
      # WORDPRESS_CONST_NAME: "your value"
      # PHPINI_name: "your value"
    networks:
      - wordpress
    depends_on: &wordpress_depends_on
      mysql:
        condition: service_healthy
      mailhog:
        condition: service_started

  devcontainer:
    build:
      context: .
      dockerfile: wordpress-base.Dockerfile
      target: devcontainer
      # args:
      #   TAG: php8.1
    environment: *wordpress_environment
    networks:
      - wordpress
    depends_on: *wordpress_depends_on
    # extra_hosts:
    #   # For debugging from host machine.
    #   - "host.docker.internal:host-gateway"


networks:
  wordpress:
