services:

  # https://hub.docker.com/_/mysql
  mysql:
    image: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME:-wordpress}
      MYSQL_USER: ${WORDPRESS_DB_USER:-wordpress}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD:-wordpress}
    # https://stackoverflow.com/a/54854239/3622941
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 30s
      interval: 5s
      timeout: 5s
      retries: 55
    networks:
      - wordpress


  # https://hub.docker.com/r/selenium/standalone-chrome
  # https://github.com/SeleniumHQ/docker-selenium
  # http://localhost:4444 --> Sessions --> Recording icon like 📹--> LiveView with password "secret"
  selenium:
    image: selenium/standalone-chrome
    environment:
      LANGUAGE: ja_JP.UTF-8
    healthcheck:
      test: /opt/bin/check-grid.sh --host 0.0.0.0 --port 4444
      interval: 15s
      timeout: 30s
      retries: 5
    shm_size: 2g
    ports:
      - "4444:4444"
    networks:
      - wordpress


  # https://hub.docker.com/_/wordpress
  wordpress:
    build:
      context: .
      dockerfile: wordpress-base.Dockerfile
      # args:
      #   TAG: php8.1
    healthcheck:
      test: bash -c "[ -f /var/www/wp-setup.complete ]"
      start_period: 30s
      interval: 5s
      timeout: 5s
      retries: 55
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME:-wordpress}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER:-wordpress}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD:-wordpress}
      # WORDPRESS_SETUP_SCRIPT: "/var/www/html/.workspace/PATH/TO/SETUP_SCRIPT.sh"
      WORDPRESS_CONFIG_EXTRA: |+
        // AT FIRST, define debug settings.
        error_reporting( E_ALL & ~E_NOTICE );
        @ini_set( 'display_errors', 1 );
        defined( 'AUTOMATIC_UPDATER_DISABLED' ) || define( 'AUTOMATIC_UPDATER_DISABLED', true );
        require_once '/var/www/html/.workspace/.devcontainer/utils/spoofing-hostport.php';
        require_once '/var/www/html/.workspace/.devcontainer/utils/mail-fetcher.php';
        require_once '/var/www/html/.workspace/.devcontainer/utils/prevent-sendmail.php';
        require_once '/var/www/html/.workspace/.devcontainer/utils/wpcli-role-import-export.php';
      # WORDPRESS_DEBUG: "yes"  # optional, default: no
      # WORDPRESS_INSTALL_TITLE: "WordPress in devcontainer"  # optional, default: WordPress in docker
      # WORDPRESS_INSTALL_ADMIN_USER: "admin"  # optional, default: admin
      # WORDPRESS_INSTALL_ADMIN_PASSWORD: "password"  # optional, default: password
      # WORDPRESS_INSTALL_ADMIN_EMAIL: "admin@wordpress.local"  # optional, default: admin@wordpress.local
      # WORDPRESS_LOCALE: "en_US"  # optional, default: en_US
    networks:
      - wordpress
    depends_on:
      mysql:
        condition: service_healthy
    # extra_hosts:
    #   # For debugging from host machine.
    #   - "host.docker.internal:host-gateway"


networks:
  wordpress:
