services:

  mysql:
    extends:
      file: common.yml
      service: mysql


  mailhog:
    extends:
      file: common.yml
      service: mailhog


  selenium:
    extends:
      file: common.yml
      service: selenium


  wordpress:
    extends:
      file: common.yml
      service: wordpress
    volumes:
      - "/var/www/html/.workspace:/var/www/html/.workspace:ro"
      - "/var/www/html/wp-content/plugins:/var/www/html/wp-content/plugins:ro"
      - "/var/www/html/wp-content/themes:/var/www/html/wp-content/themes:ro"


  php:
    build:
      args:
        TAG: 8.0-cli
      dockerfile_inline: |+
        ARG TAG=8.0-cli
        FROM php:$${TAG}
        RUN apt-get update; \
            apt-get install -yq git unzip mariadb-client
        RUN pecl install xdebug; \
          { \
              echo 'xdebug.idekey=VSCODE'; \
              echo 'xdebug.mode=develop,debug'; \
              #echo 'xdebug.start_with_request=trigger'; \
              #echo 'xdebug.log=/tmp/xdebug.log'; \
              echo 'xdebug.client_host=host.docker.internal'; \
              #echo 'xdebug.client_port=9003'; \
          } | tee $PHP_INI_DIR/conf.d/docker-php-ext-xdebug-config.ini; \
          docker-php-ext-enable xdebug
        RUN curl -sL https://getcomposer.org/installer | php; \
            mv composer.phar /usr/local/bin/composer; \
            mkdir /var/www/.composer; \
            chown www-data:www-data /var/www/.composer
        ENV PATH="/root/.composer/vendor/bin/:${PATH}"
        RUN curl -sL https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar -o wp; \
            chmod +x wp; \
            mv wp /usr/local/bin/
    depends_on:
      selenium:
        condition: service_healthy
      wordpress:
        condition: service_healthy
    volumes:
      - "/var/www/html/.workspace:/var/www/html/.workspace:ro"
    stdin_open: true
    tty: true
    working_dir: /var/www/html/.workspace
    command: [ "exit", "1" ]
    networks:
      - wordpress
    extra_hosts:
      - host.docker.internal:host-gateway
    # environment:
    #   XDEBUG_TRIGGER: "1"


networks:
  wordpress:
